# Generated by Django 3.1.12 on 2021-12-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentdate', models.DateField(max_length=10)),
                ('appointmenttime', models.TimeField(max_length=10)),
                ('symptoms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('insurance_policy', models.CharField(max_length=50)),
                ('passport', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.BooleanField()),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='OnShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_beg', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_beg', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('appointmentresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.appointmentresult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.room')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentresult',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.diseases'),
        ),
        migrations.AddField(
            model_name='appointmentresult',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.prescription'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.patient'),
        ),
    ]
