# Generated by Django 3.1.12 on 2022-01-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onshift',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.receptionist'),
        ),
    ]
