# Generated by Django 3.1.12 on 2022-01-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220112_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onshift',
            name='date_beg',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='onshift',
            name='date_end',
            field=models.DateField(),
        ),
    ]
