# Generated by Django 3.1.12 on 2022-01-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_appointment_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='staus',
            new_name='status',
        ),
    ]
